from PIL import Image
from colors import colorsDict, backgroundLookup
from traitEncodings import TRAIT_ENCODINGS

def drawCap(im, primaryColor, shadeColor1, shadeColor2, lightColor, backgroundColor):
    imNew = Image.new('RGBA', (32, 32), (0, 0, 0, 0))

    # imNew.putpixel((12, 6), backgroundLookup[backgroundColor])
    # imNew.putpixel((13, 6), backgroundLookup[backgroundColor])
    # imNew.putpixel((14, 6), backgroundLookup[backgroundColor])
    # imNew.putpixel((15, 6), backgroundLookup[backgroundColor])
    # imNew.putpixel((16, 6), backgroundLookup[backgroundColor])
    # imNew.putpixel((17, 6), backgroundLookup[backgroundColor])

    # imNew.putpixel((9, 7), backgroundLookup[backgroundColor])
    # imNew.putpixel((10, 7), backgroundLookup[backgroundColor])
    # imNew.putpixel((11, 7), backgroundLookup[backgroundColor])
    imNew.putpixel((13, 7), colorsDict["black"])
    imNew.putpixel((14, 7), colorsDict["black"])
    imNew.putpixel((15, 7), colorsDict["black"])
    imNew.putpixel((16, 7), colorsDict["black"])
    imNew.putpixel((17, 7), colorsDict["black"])
    imNew.putpixel((18, 7), colorsDict["black"])
    # imNew.putpixel((19, 7), backgroundLookup[backgroundColor])
    # imNew.putpixel((20, 7), backgroundLookup[backgroundColor])
    # imNew.putpixel((21, 7), backgroundLookup[backgroundColor])

    # imNew.putpixel((8, 8), backgroundLookup[backgroundColor])
    # imNew.putpixel((9, 8), backgroundLookup[backgroundColor])
    # imNew.putpixel((10, 8), backgroundLookup[backgroundColor])
    imNew.putpixel((12, 8), colorsDict["black"])
    imNew.putpixel((13, 8), colorsDict[shadeColor2])
    imNew.putpixel((14, 8), colorsDict[shadeColor1])
    imNew.putpixel((15, 8), colorsDict[shadeColor1])
    imNew.putpixel((16, 8), colorsDict[shadeColor1])
    imNew.putpixel((17, 8), colorsDict[shadeColor1])
    imNew.putpixel((18, 8), colorsDict[primaryColor])
    imNew.putpixel((19, 8), colorsDict["black"])
    # imNew.putpixel((21, 8), backgroundLookup[backgroundColor])
    # imNew.putpixel((21, 8), backgroundLookup[backgroundColor])
    # imNew.putpixel((22, 8), backgroundLookup[backgroundColor])

    # imNew.putpixel((8, 9), backgroundLookup[backgroundColor])
    imNew.putpixel((10, 9), backgroundLookup[backgroundColor])
    imNew.putpixel((11, 9), colorsDict["black"])
    imNew.putpixel((12, 9), colorsDict[shadeColor2])
    imNew.putpixel((13, 9), colorsDict[shadeColor1])
    imNew.putpixel((14, 9), colorsDict[shadeColor1])
    imNew.putpixel((15, 9), colorsDict[shadeColor1])
    imNew.putpixel((16, 9), colorsDict[primaryColor])
    imNew.putpixel((17, 9), colorsDict[primaryColor])
    imNew.putpixel((18, 9), colorsDict[primaryColor])
    imNew.putpixel((19, 9), colorsDict[lightColor])
    imNew.putpixel((20, 9), colorsDict["black"])
    imNew.putpixel((21, 9), backgroundLookup[backgroundColor])
    # imNew.putpixel((22, 9), backgroundLookup[backgroundColor])

    imNew.putpixel((9, 10), backgroundLookup[backgroundColor])
    imNew.putpixel((10, 10), colorsDict["black"])
    imNew.putpixel((11, 10), colorsDict[shadeColor2])
    imNew.putpixel((12, 10), colorsDict[shadeColor1])
    imNew.putpixel((13, 10), colorsDict[shadeColor1])
    imNew.putpixel((14, 10), colorsDict[shadeColor1])
    imNew.putpixel((15, 10), colorsDict["black"])
    imNew.putpixel((16, 10), colorsDict["black"])
    imNew.putpixel((17, 10), colorsDict["black"])
    imNew.putpixel((18, 10), colorsDict[primaryColor])
    imNew.putpixel((19, 10), colorsDict[primaryColor])
    imNew.putpixel((20, 10), colorsDict[lightColor])
    imNew.putpixel((21, 10), colorsDict["black"])
    imNew.putpixel((22, 10), backgroundLookup[backgroundColor])

    imNew.putpixel((9, 11), backgroundLookup[backgroundColor])
    imNew.putpixel((10, 11), colorsDict["black"])
    imNew.putpixel((11, 11), colorsDict[shadeColor2])
    imNew.putpixel((12, 11), colorsDict[shadeColor1])
    imNew.putpixel((13, 11), colorsDict[shadeColor1])
    imNew.putpixel((14, 11), colorsDict["black"])
    imNew.putpixel((18, 11), colorsDict["black"])
    imNew.putpixel((19, 11), colorsDict[primaryColor])
    imNew.putpixel((20, 11), colorsDict[primaryColor])
    imNew.putpixel((21, 11), colorsDict["black"])
    imNew.putpixel((22, 11), backgroundLookup[backgroundColor])

    imNew.putpixel((7, 12), colorsDict["black"])
    imNew.putpixel((8, 12), colorsDict["black"])
    imNew.putpixel((9, 12), colorsDict["black"])
    imNew.putpixel((10, 12), colorsDict["black"])
    imNew.putpixel((11, 12), colorsDict[shadeColor1])
    imNew.putpixel((12, 12), colorsDict[shadeColor1])
    imNew.putpixel((13, 12), colorsDict[shadeColor1])
    imNew.putpixel((14, 12), colorsDict["black"])
    imNew.putpixel((15, 12), colorsDict["black"])
    imNew.putpixel((16, 12), colorsDict["black"])
    imNew.putpixel((17, 12), colorsDict["black"])
    imNew.putpixel((18, 12), colorsDict["black"])
    imNew.putpixel((19, 12), colorsDict[primaryColor])
    imNew.putpixel((20, 12), colorsDict[primaryColor])
    imNew.putpixel((21, 12), colorsDict["black"])
    imNew.putpixel((22, 12), backgroundLookup[backgroundColor])

    imNew.putpixel((6, 13), colorsDict["black"])
    imNew.putpixel((7, 13), colorsDict[shadeColor2])
    imNew.putpixel((8, 13), colorsDict[shadeColor2])
    imNew.putpixel((9, 13), colorsDict[shadeColor2])
    imNew.putpixel((10, 13), colorsDict["black"])
    imNew.putpixel((11, 13), colorsDict[shadeColor1])
    imNew.putpixel((12, 13), colorsDict[primaryColor])
    imNew.putpixel((13, 13), colorsDict[primaryColor])
    imNew.putpixel((14, 13), colorsDict[primaryColor])
    imNew.putpixel((15, 13), colorsDict[primaryColor])
    imNew.putpixel((16, 13), colorsDict[primaryColor])
    imNew.putpixel((17, 13), colorsDict[primaryColor])
    imNew.putpixel((18, 13), colorsDict[primaryColor])
    imNew.putpixel((19, 13), colorsDict[primaryColor])
    imNew.putpixel((20, 13), colorsDict[primaryColor])
    imNew.putpixel((21, 13), colorsDict["black"])

    imNew.putpixel((6, 14), colorsDict["black"])
    imNew.putpixel((7, 14), colorsDict["black"])
    imNew.putpixel((8, 14), colorsDict["black"])
    imNew.putpixel((9, 14), colorsDict["black"])
    imNew.putpixel((10, 14), colorsDict["black"])
    imNew.putpixel((11, 14), colorsDict["black"])
    imNew.putpixel((12, 14), colorsDict["black"])
    imNew.putpixel((13, 14), colorsDict["black"])
    imNew.putpixel((14, 14), colorsDict["black"])
    imNew.putpixel((15, 14), colorsDict["black"])
    imNew.putpixel((16, 14), colorsDict["black"])
    imNew.putpixel((17, 14), colorsDict["black"])
    imNew.putpixel((18, 14), colorsDict["black"])
    imNew.putpixel((19, 14), colorsDict["black"])
    imNew.putpixel((20, 14), colorsDict["black"])
    imNew.putpixel((21, 14), colorsDict["black"])

    im.paste(imNew, (0,0), mask=imNew)
